services:
  kudosbot:
    container_name: kudosbot
    image: kudosbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7212:7212"
    volumes:
      - .:/app
      - ./slackapp.db:/app/slackapp.db
    command: uvicorn src.main:app --host 0.0.0.0 --port 7212 --env-file .env
