version: "3"
services:
  kudosbot:
    image: kudosbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --env-file .env
